export * from "./schema";
export {
  acceptanceDecisions,
  agentRuns,
  agents,
  approvals,
  artifacts,
  auditEvents,
  budgets,
  capabilityManifests,
  defects,
  githubAppInstallations,
  interfaceContracts,
  organizations,
  prdVersions,
  projects,
  pullRequests,
  repositories,
  reviewRecords,
  requirements,
  testCases,
  testRuns,
  workItems,
  workspaceRuns
} from "./schema";
export * from "./repository";

import {
  acceptanceDecisions,
  agentRuns,
  agents,
  approvals,
  artifacts,
  auditEvents,
  budgets,
  capabilityManifests,
  defects,
  githubAppInstallations,
  interfaceContracts,
  organizations,
  prdVersions,
  projects,
  pullRequests,
  repositories,
  reviewRecords,
  requirements,
  testCases,
  testRuns,
  workItems,
  workspaceRuns
} from "./schema";

export const patchPilotTables = {
  acceptanceDecisions,
  agentRuns,
  agents,
  approvals,
  artifacts,
  auditEvents,
  budgets,
  capabilityManifests,
  defects,
  githubAppInstallations,
  interfaceContracts,
  organizations,
  prdVersions,
  projects,
  pullRequests,
  repositories,
  reviewRecords,
  requirements,
  testCases,
  testRuns,
  workItems,
  workspaceRuns
} as const;

export const patchPilotTableNames = [
  "acceptance_decisions",
  "agent_runs",
  "agents",
  "approvals",
  "artifacts",
  "audit_events",
  "budgets",
  "capability_manifests",
  "defects",
  "github_app_installations",
  "interface_contracts",
  "organizations",
  "prd_versions",
  "projects",
  "pull_requests",
  "repositories",
  "review_records",
  "requirements",
  "test_cases",
  "test_runs",
  "work_items",
  "workspace_runs"
] as const;

export type PatchPilotTableName = (typeof patchPilotTableNames)[number];
